// <auto-generated />
using System;
using CRUD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUD.Migrations.salary
{
    [DbContext(typeof(salaryContext))]
    [Migration("20200225193255_Salary")]
    partial class Salary
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUD.Models.Salarys", b =>
                {
                    b.Property<int>("salaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("emp_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("endingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("salary")
                        .HasColumnType("int");

                    b.Property<DateTime>("startingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("salaryId");

                    b.ToTable("Salary");
                });
#pragma warning restore 612, 618
        }
    }
}
